The ``0-add_integer`` module
======================

Example 1: This module serves as unit test for the add_integer function
    >>> add_integer = __import__('0-add_integer').add_integer
    >>> add_integer(5, 4)
    3

Example 2: The add_integer function works also with float numbers

    >>> add_integer(25.7, 33.6)
    55

Example 3: it works also with two floats negative numbers

    >>> add_integer(-2.5, -3.7)
    -5

Example 4: it works also with one integer number and one float number

    >>> add_integer(7, 3.8)
    10

Example 5: it works also with only one argument, thesecond argument defaults to 98

    >>> add_integer(12)
    110

Example 6: if no arguments are provided, a TypeError is raised
with a message "a must be an integer":

    >>> add_integer(None)
    Traceback (most recent call last):
    TypeError: a must be an integer

Example 7: if the second argument is not provided, a TypeError
is raised with a message "b lust be an integer":

    >>> add_integer(17, None)
    Traceback (most recent call last):
    TypeError: b must be an integer

Example 8: if the first argument is not an integer, a TypeError
is raised with a message "a must be an integer":

    >>> add_integer("hello", 4)
    Traceback (most recent call last):
    TypeError: a must be an integer

Example 9: if the second argument is not an integer, a TypeError
is raised with a message "b must be an integer":

    >>> add_integer(4, "hello")
    Traceback (most recent call last):
    TypeError: b must be an integer

Example 10: if the first argument is not defined as variable, a NameError
is raised with a message "name 'txt' is not defined":

    >>> add_integer(txt, 4)
    Traceback (most recent call last):
    NameError: name 'txt' is not defined

Example 11: if both arguments are not defined as variables, a NameError
is raised with a message "name 'txt1' is not defined":

    >>> add_integer(txt1, txt2)
    Traceback (most recent call last):
    NameError: name 'txt1' is not defined

Example 12: if both arguments are not integers, a TypeError
is raised with a message "a must be an integer":

    >>> add_integer("txt1", "txt2")
    Traceback (most recent call last):
    TypeErro: a must be an integer
